# Generated by Django 3.2.6 on 2021-08-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="General",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("basic_access", "Can access the AA-Survey module"),
                    ("manage_survey", "Can manage the AA-Survey module"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
