# Generated by Django 3.2.6 on 2021-08-28 11:36

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "aa_survey",
            "0002_survey_surveychoice_surveyform_surveyquestion_surveyresponse",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyform",
            name="open_until",
            field=models.DateTimeField(
                blank=True,
                help_text="This survey is available until ... (Optional: If no date is set, the survey will be available until it is no longer marked as active.)",
                null=True,
                verbose_name="Available until",
            ),
        ),
        migrations.AlterField(
            model_name="surveyform",
            name="description",
            field=models.TextField(
                help_text="Quick description what this survey is about ...",
                verbose_name="Survey Description",
            ),
        ),
        migrations.AlterField(
            model_name="surveyform",
            name="name",
            field=models.CharField(
                help_text="Give your survey a good and descriptive name",
                max_length=254,
                verbose_name="Survey Name",
            ),
        ),
    ]
