# Generated by Django 3.2.6 on 2021-08-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "aa_survey",
            "0002_survey_surveychoice_surveyform_surveyquestion_surveyresponse",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surveyform",
            name="created_by",
        ),
        migrations.AlterField(
            model_name="surveyform",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
