# Generated by Django 3.2.6 on 2021-08-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_survey", "0003_auto_20210827_0822"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyform",
            name="name",
            field=models.CharField(
                blank=True, max_length=254, null=True, verbose_name="Survey Name"
            ),
        ),
    ]
