# Generated by Django 3.2.6 on 2021-08-28 14:33

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aa_survey", "0003_auto_20210828_1136"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="surveyform",
            options={"default_permissions": (), "ordering": ["-pk"]},
        ),
        migrations.AlterField(
            model_name="surveyform",
            name="open_until",
            field=models.DateTimeField(
                blank=True,
                help_text="This survey is available until (Eve Time) ... (Optional: If no date is set, the survey will be available until it is no longer marked as active.)",
                null=True,
                verbose_name="Available until",
            ),
        ),
    ]
