# Generated by Django 3.2.6 on 2021-08-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_survey", "0004_alter_surveyform_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyquestion",
            name="help_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
