# Generated by Django 3.2.6 on 2021-08-31 22:29

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aa_survey", "0004_auto_20210828_1433"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyquestion",
            name="mandatory",
            field=models.BooleanField(default=False),
        ),
    ]
