# Generated by Django 4.0.10 on 2023-09-14 19:24

# Django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aa_survey", "0006_alter_surveyquestion_help_text_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SurveyQuestion",
            new_name="Question",
        ),
    ]
