# Generated by Django 4.0.10 on 2023-09-14 19:24

# Django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aa_survey", "0007_rename_surveyquestion_question"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SurveyChoice",
            new_name="Choice",
        ),
    ]
